docker-builder:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE_FRONTEND ./frontend/
    - docker build --pull -t $CI_REGISTRY_IMAGE_BACKEND ./backend/
    - docker push $CI_REGISTRY_IMAGE_FRONTEND
    - docker push $CI_REGISTRY_IMAGE_BACKEND
  only:
    - main
  when: manual

run tests:
  stage: test
  image: python:3
  script:
    - pip install pytest coverage
    - cd backend && pipenv install && pipenv shell && cd ..
    - coverage run -m pytest
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

