docker-builder:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE_FRONTEND ./frontend/
    - docker build --pull -t $CI_REGISTRY_IMAGE_BACKEND ./backend/
    - docker push $CI_REGISTRY_IMAGE_FRONTEND
    - docker push $CI_REGISTRY_IMAGE_BACKEND
  only:
    - main
  when: manual

stages:
  - code review
  - testing

flake8:
  stage: code review
  allow_failure: true
  script:
  - flake8 --max-line-length=120 *.py
  only:
    - merge_requests
    - main

pylint:
  stage: code review
  allow_failure: true
  script:
  - pylint -d C0301 *.py
  only:
    - merge_requests
    - main

test:
  stage: testing
  image: python:3.8
  script:
    - pip install pytest coverage pipenv
    - cd backend && pipenv install --system --deploy --ignore-pipfile && cd ..
    - coverage run -m pytest
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  only:
    - merge_requests
    - main

    

