docker-builder:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE_FRONTEND ./frontend/
    - docker build --pull -t $CI_REGISTRY_IMAGE_BACKEND ./backend/
    - docker push $CI_REGISTRY_IMAGE_FRONTEND
    - docker push $CI_REGISTRY_IMAGE_BACKEND
  only:
    - main
  when: manual

test:
  stage: test
  image: python:3.8
  script:
    - pip install pytest coverage pipenv
    - cd backend && pipenv install --system --deploy --ignore-pipfile && cd ..
    - coverage run -m pytest
    - coverage report
    - coverage xml
    - coverage html
  artifacts:
    reports:
      cobertura: coverage.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
    # delete everything in the current public folder
    # and replace with code coverage HTML report
    - rm -rf public/*
    - cp -r htmlcov* public/
  artifacts:
    paths:
      - public
    expire_in: 10 days

