repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        args:
        - --fail-under=7 # Thresehold out of 10 the pylint test will fail under.
        - --disable=F0401 # This ignores cannot import error.
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3.8