version: "3.9"

services:
  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - backend

  backend:
    build: ./backend/
    container_name: backend
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://newuser:newpassword@mysql:3306/test_db
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    build: ./nginx/ 
    container_name: nginx
    restart: always
    expose: 
      - 80
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=newpassword
    expose:
      - 3306
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 0.0.0.0 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_admin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql

volumes:
  dbdata:
