"""first commit

Revision ID: de6fff7ff1bb
Revises: 
Create Date: 2022-01-20 20:09:47.002055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de6fff7ff1bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
